(() => {
  'use strict';
  if (!window.supabase || typeof shell !== 'function') return;

  const client=window.supabase.createClient('https://tckvzlizcqdxzgavjwie.supabase.co','sb_publishable_MRtiWP-ErwVKXqNbGFrW_g_FwEHsob3');
  const safe=s=>typeof esc==='function'?esc(s):String(s??'');
  const fmt=v=>v?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(v)):'—';
  const canManage=cid=>Boolean(window.CondoAccess?.can('assemblies.manage',cid));
  const canReview=cid=>Boolean(window.CondoAccess?.canAccessCondo(cid));
  const choiceLabel={yes:'Sim',no:'Não',abstain:'Abstenção'};
  const statusLabel={planned:'Planejada',called:'Convocada',in_progress:'Em andamento',held:'Realizada',cancelled:'Cancelada'};
  const agendaStatus={draft:'Rascunho',open:'Votação aberta',closed:'Encerrada',cancelled:'Cancelada'};
  async function currentUser(){return (await client.auth.getSession()).data.session?.user||null}

  async function loadAssembly(id){
    const [{data:a,error:ae},{data:items,error:ie},{data:att,error:ate},{data:results,error:re},{data:votes,error:ve},{data:units,error:ue}]=await Promise.all([
      client.from('assemblies').select('*').eq('id',id).single(),
      client.from('assembly_agenda_items').select('*').eq('assembly_id',id).order('sort_order').order('created_at'),
      client.from('assembly_attendance').select('*').eq('assembly_id',id).order('checked_in_at'),
      client.from('assembly_vote_results').select('*').eq('assembly_id',id),
      client.from('assembly_votes').select('*').eq('assembly_id',id),
      client.from('units').select('id,block_name,unit_number').order('block_name').order('unit_number')
    ]);
    if(ae)throw ae;if(ie)throw ie;if(ate)throw ate;if(re)throw re;if(ve)throw ve;if(ue)throw ue;
    return {a,items:items||[],att:att||[],results:results||[],votes:votes||[],units:(units||[]).filter(u=>u.id&&a&&true)};
  }
  function unitName(u){return [u?.block_name,u?.unit_number].filter(Boolean).join(' / ')||'Unidade'}
  function resultFor(i,results){return results.find(r=>r.agenda_item_id===i.id)||{yes_votes:0,no_votes:0,abstain_votes:0,yes_weight:0,no_weight:0,abstain_weight:0,present_units:0,eligible_units:0,present_weight:0}}
  function decision(i,r){
    const yes=Number(r.yes_weight||0), no=Number(r.no_weight||0), abst=Number(r.abstain_weight||0);
    const denom=i.threshold_basis==='present_weight'?Number(r.present_weight||0):(yes+no+abst);
    if(!denom)return {label:'Sem votos',pct:0,cls:'attention'};
    const pct=yes/denom*100;return {label:pct>=Number(i.approval_threshold_percent)?'Atingiu regra configurada':'Não atingiu regra',pct,cls:pct>=Number(i.approval_threshold_percent)?'good':'warn'};
  }

  async function listPage(cid){
    const c=condo(cid);if(!c||!canReview(cid))return;
    const action=canManage(cid)?`<button class="btn btn-primary" onclick="openAssemblyModal('${cid}')">+ Nova assembleia</button>`:'';
    $('#app').innerHTML=shell(`${topbar('Assembleias',`${safe(c.name)} • reuniões, presença, pautas e votações.`,'Workspace',action)}<article class="panel"><div class="panel-body"><div class="empty">Carregando...</div></div></article>`,'condo-assemblies',cid);
    const {data:rows,error}=await client.from('assemblies').select('*').eq('condominium_id',cid).order('scheduled_at',{ascending:false});if(error)return flash(error.message);
    const cards=(rows||[]).map(a=>`<article class="card" style="margin-bottom:12px"><div style="display:flex;justify-content:space-between;gap:16px;align-items:flex-start"><div><div class="eyebrow">${fmt(a.scheduled_at)}</div><h3 style="margin:5px 0">${safe(a.title)}</h3><p class="muted">📍 ${safe(a.location||'Local a definir')}</p></div><div class="row-actions"><span class="badge ${a.status==='held'?'good':a.status==='cancelled'?'bad':a.status==='in_progress'?'warn':'attention'}">${safe(statusLabel[a.status]||a.status)}</span><button class="btn btn-soft" onclick="openAssemblyWorkspace('${a.id}','${cid}')">Abrir</button></div></div></article>`).join('')||'<div class="empty">Nenhuma assembleia cadastrada.</div>';
    $('#app').innerHTML=shell(`${topbar('Assembleias',`${safe(c.name)} • reuniões, presença, pautas e votações.`,'Workspace',action)}<div class="database-explainer"><div class="database-icon">🏛️</div><div><strong>Votação com regra configurável por pauta.</strong><p>O sistema registra presença por unidade, representante, peso e resultado. A regra de aprovação é definida em cada pauta, porque o quórum aplicável pode variar.</p></div></div><section>${cards}</section>`,'condo-assemblies',cid);
  }

  async function workspace(id,cid){
    if(!canReview(cid))return;
    $('#app').innerHTML=shell(`${topbar('Assembleia','Carregando workspace...','Workspace','')}<article class="panel"><div class="panel-body"><div class="empty">Carregando assembleia...</div></div></article>`,'condo-assemblies',cid);
    try{
      const {a,items,att,results,votes,units}=await loadAssembly(id); const manage=canManage(cid); const unitMap=new Map(units.map(u=>[u.id,u]));
      const eligible=units.filter(u=>u.id&&String(a.condominium_id)===String(cid));
      const presentWeight=att.filter(x=>x.can_vote).reduce((s,x)=>s+Number(x.vote_weight||0),0);
      const head=`<div class="grid-2" style="margin-bottom:18px"><article class="panel"><div class="panel-body"><div class="eyebrow">${fmt(a.scheduled_at)}</div><h2>${safe(a.title)}</h2><p class="muted" style="margin-top:6px">📍 ${safe(a.location||'Local a definir')}</p>${a.agenda?`<p style="margin-top:12px">${safe(a.agenda)}</p>`:''}<div style="margin-top:14px"><span class="badge ${a.status==='held'?'good':a.status==='cancelled'?'bad':a.status==='in_progress'?'warn':'attention'}">${safe(statusLabel[a.status]||a.status)}</span></div></div></article><article class="panel"><div class="panel-body"><div class="kpi-strip"><div class="kpi-pill"><strong>${att.length}</strong><span>Unidades presentes</span></div><div class="kpi-pill"><strong>${eligible.length}</strong><span>Unidades cadastradas</span></div><div class="kpi-pill"><strong>${presentWeight}</strong><span>Peso presente</span></div></div>${manage?`<div class="row-actions" style="margin-top:16px"><button class="btn" onclick="openAssemblyStatusModal('${a.id}')">Status</button><button class="btn btn-primary" onclick="openAttendanceModal('${a.id}','${cid}')">+ Presença</button><button class="btn" onclick="openAgendaItemModal('${a.id}','${cid}')">+ Pauta</button></div>`:''}</div></article></div>`;
      const attendance=`<article class="panel" style="margin-bottom:18px"><div class="panel-head"><div><h2>Lista de presença</h2><div class="muted small">Uma linha por unidade, com representante e peso de voto.</div></div></div><div class="panel-body"><div class="table-wrap"><table class="table"><thead><tr><th>Unidade</th><th>Representante</th><th>Tipo</th><th>Peso</th><th>Vota?</th></tr></thead><tbody>${att.length?att.map(x=>`<tr><td><strong>${safe(unitName(unitMap.get(x.unit_id)))}</strong></td><td>${safe(x.representative_name||'Usuário vinculado')}</td><td>${safe(x.representation_type)}</td><td>${Number(x.vote_weight||1)}</td><td>${x.can_vote?'Sim':'Não'}</td></tr>`).join(''):'<tr><td colspan="5"><div class="empty">Nenhuma presença registrada.</div></td></tr>'}</tbody></table></div></div></article>`;
      const agenda=items.length?items.map(i=>{const r=resultFor(i,results),d=decision(i,r),itemVotes=votes.filter(v=>v.agenda_item_id===i.id);return `<article class="panel" style="margin-bottom:14px"><div class="panel-head"><div><div class="eyebrow">${safe(agendaStatus[i.status]||i.status)}</div><h2>${safe(i.title)}</h2><div class="muted small">Regra: ${Number(i.approval_threshold_percent)}% sobre ${i.threshold_basis==='present_weight'?'peso presente':'votos válidos configurados'}</div></div>${manage?`<div class="row-actions"><button class="btn" onclick="openAgendaStatusModal('${i.id}','${cid}','${id}')">Status</button>${i.status==='open'?`<button class="btn btn-primary" onclick="openManagementVoteModal('${i.id}','${id}','${cid}')">Registrar voto</button>`:''}</div>`:''}</div><div class="panel-body">${i.description?`<p style="margin-bottom:14px">${safe(i.description)}</p>`:''}<div class="kpi-strip"><div class="kpi-pill"><strong>${r.yes_votes}</strong><span>Sim (${Number(r.yes_weight)})</span></div><div class="kpi-pill"><strong>${r.no_votes}</strong><span>Não (${Number(r.no_weight)})</span></div><div class="kpi-pill"><strong>${r.abstain_votes}</strong><span>Abstenção (${Number(r.abstain_weight)})</span></div><div class="kpi-pill"><strong>${d.pct.toFixed(1)}%</strong><span>${safe(d.label)}</span></div></div><div class="muted small" style="margin-top:12px">${itemVotes.length} voto(s) registrado(s). O sistema compara apenas com a regra configurada nesta pauta, não substitui a análise da convenção ou da regra legal aplicável.</div></div></article>`}).join(''):'<article class="panel"><div class="panel-body"><div class="empty">Nenhuma pauta cadastrada.</div></div></article>';
      $('#app').innerHTML=shell(`${topbar('Assembleia',`${safe(condo(cid)?.name||'Condomínio')} • workspace da reunião.`,'Workspace',`<button class="btn" onclick="location.hash='#/condominio/${cid}/assembleias'">← Voltar</button>`)}${head}${attendance}<section>${agenda}</section>`,'condo-assemblies',cid);
    }catch(err){flash(err.message||'Não foi possível carregar a assembleia.')}
  }

  window.openAssemblyWorkspace=(id,cid)=>{location.hash=`#/condominio/${cid}/assembleias/${id}`};

  window.openAttendanceModal=async function(assemblyId,cid){
    if(!canManage(cid))return;const u=await currentUser();if(!u)return;const [{data:units},{data:members}]=await Promise.all([client.from('units').select('id,block_name,unit_number').eq('condominium_id',cid).order('block_name').order('unit_number'),client.from('condominium_members').select('user_id,unit_id,member_type').eq('condominium_id',cid).eq('role','resident').eq('is_active',true)]);
    modal(`<div class="eyebrow">Presença</div><h2 style="margin-bottom:16px">Registrar unidade presente</h2><form id="attendance-form" class="form-grid"><div class="field"><label>Unidade</label><select name="unit" required>${(units||[]).map(x=>`<option value="${x.id}">${safe(unitName(x))}</option>`).join('')}</select></div><div class="field"><label>Representante vinculado</label><select name="user"><option value="">Outro / procuração</option>${(members||[]).map(x=>`<option value="${x.user_id}" data-unit="${x.unit_id||''}">${safe(x.member_type||'Morador')} • ${safe(unitName((units||[]).find(y=>y.id===x.unit_id)))}</option>`).join('')}</select></div><div class="field full"><label>Nome do representante</label><input name="name" placeholder="Preencher quando não houver usuário vinculado"></div><div class="field"><label>Representação</label><select name="type"><option value="owner">Proprietário</option><option value="tenant">Inquilino autorizado</option><option value="proxy">Procuração</option><option value="management_recorded">Registrado pela gestão</option><option value="other">Outro</option></select></div><div class="field"><label>Peso do voto</label><input name="weight" type="number" step="0.0001" min="0.0001" value="1" required></div><div class="field"><label><input type="checkbox" name="canVote" checked> Unidade apta a votar</label></div><div class="field full"><label>Observações</label><textarea name="notes"></textarea></div><div class="field full"><button class="btn btn-primary">Registrar presença</button></div></form>`);
    $('#attendance-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),payload={assembly_id:assemblyId,condominium_id:cid,unit_id:f.get('unit'),representative_user_id:f.get('user')||null,representative_name:String(f.get('name')).trim()||null,representation_type:f.get('type'),can_vote:f.get('canVote')==='on',vote_weight:Number(f.get('weight')||1),checked_in_by:u.id,notes:String(f.get('notes')).trim()||null};const {error}=await client.from('assembly_attendance').upsert(payload,{onConflict:'assembly_id,unit_id'});if(error)return flash(error.message);closeModal();flash('Presença registrada.');workspace(assemblyId,cid)};
  };

  window.openAgendaItemModal=async function(assemblyId,cid){
    if(!canManage(cid))return;const u=await currentUser();if(!u)return;
    modal(`<div class="eyebrow">Nova pauta</div><h2 style="margin-bottom:16px">Adicionar item para deliberação</h2><form id="agenda-item-form" class="form-grid"><div class="field full"><label>Título</label><input name="title" required></div><div class="field full"><label>Descrição</label><textarea name="description"></textarea></div><div class="field"><label>Regra configurada (%)</label><input name="threshold" type="number" min="0.01" max="100" step="0.01" value="50" required></div><div class="field"><label>Base da regra</label><select name="basis"><option value="valid_votes">Votos registrados</option><option value="present_weight">Peso presente</option></select></div><div class="field"><label>Resultado para moradores</label><select name="visibility"><option value="after_close">Após encerrar</option><option value="live">Ao vivo</option><option value="management">Somente gestão</option></select></div><div class="field full"><div class="database-explainer"><div class="database-icon">⚖️</div><div><strong>Atenção à regra da pauta.</strong><p>Este percentual é configurável e não é uma recomendação jurídica. Deve refletir a regra aplicável àquela deliberação.</p></div></div></div><div class="field full"><button class="btn btn-primary">Adicionar pauta</button></div></form>`);
    $('#agenda-item-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const {error}=await client.from('assembly_agenda_items').insert({assembly_id:assemblyId,condominium_id:cid,title:String(f.get('title')).trim(),description:String(f.get('description')).trim()||null,status:'draft',result_visibility:f.get('visibility'),threshold_basis:f.get('basis'),approval_threshold_percent:Number(f.get('threshold')),created_by:u.id});if(error)return flash(error.message);closeModal();flash('Pauta adicionada.');workspace(assemblyId,cid)};
  };

  window.openAgendaStatusModal=async function(itemId,cid,assemblyId){
    if(!canManage(cid))return;const {data:i,error}=await client.from('assembly_agenda_items').select('*').eq('id',itemId).single();if(error)return flash(error.message);
    modal(`<div class="eyebrow">Pauta</div><h2 style="margin-bottom:16px">${safe(i.title)}</h2><form id="agenda-status-form" class="form-grid"><div class="field"><label>Status</label><select name="status">${[['draft','Rascunho'],['open','Abrir votação'],['closed','Encerrar votação'],['cancelled','Cancelar']].map(([v,l])=>`<option value="${v}" ${i.status===v?'selected':''}>${l}</option>`).join('')}</select></div><div class="field full"><button class="btn btn-primary">Salvar</button></div></form>`);$('#agenda-status-form').onsubmit=async e=>{e.preventDefault();const s=new FormData(e.target).get('status');const patch={status:s};if(s==='open'&&!i.opens_at)patch.opens_at=new Date().toISOString();if(s==='closed'&&!i.closes_at)patch.closes_at=new Date().toISOString();const {error:up}=await client.from('assembly_agenda_items').update(patch).eq('id',itemId);if(up)return flash(up.message);closeModal();flash('Pauta atualizada.');workspace(assemblyId,cid)};
  };

  window.openManagementVoteModal=async function(itemId,assemblyId,cid){
    if(!canManage(cid))return;const [{data:att},{data:units},{data:votes}]=await Promise.all([client.from('assembly_attendance').select('*').eq('assembly_id',assemblyId).eq('can_vote',true),client.from('units').select('id,block_name,unit_number').eq('condominium_id',cid),client.from('assembly_votes').select('unit_id,choice').eq('agenda_item_id',itemId)]);const um=new Map((units||[]).map(u=>[u.id,u])),vm=new Map((votes||[]).map(v=>[v.unit_id,v.choice]));modal(`<div class="eyebrow">Registrar voto</div><h2 style="margin-bottom:16px">Voto presencial / administrativo</h2><form id="management-vote-form" class="form-grid"><div class="field full"><label>Unidade presente</label><select name="unit">${(att||[]).map(a=>`<option value="${a.unit_id}">${safe(unitName(um.get(a.unit_id)))}${vm.has(a.unit_id)?` • atual: ${safe(choiceLabel[vm.get(a.unit_id)])}`:''}</option>`).join('')}</select></div><div class="field full"><label>Voto</label><select name="choice"><option value="yes">Sim</option><option value="no">Não</option><option value="abstain">Abstenção</option></select></div><div class="field full"><button class="btn btn-primary">Registrar voto</button></div></form>`);$('#management-vote-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const {error}=await client.rpc('record_assembly_vote',{p_agenda_item_id:itemId,p_unit_id:f.get('unit'),p_choice:f.get('choice')});if(error)return flash(error.message);closeModal();flash('Voto registrado.');workspace(assemblyId,cid)};
  };

  async function residentCtx(){
    const user=await currentUser();if(!user)return null;const {data:m}=await client.from('condominium_members').select('condominium_id,unit_id').eq('user_id',user.id).eq('role','resident').eq('is_active',true).limit(1).maybeSingle();if(!m)return null;const {data:c}=await client.from('condominiums').select('id,name').eq('id',m.condominium_id).single();return {user,m,c};
  }
  function residentShell(ctx,content){return `<div class="resident-app"><aside class="resident-sidebar"><div class="brand"><div class="brand-mark">SG</div><div><strong>Portal do Morador</strong><span>${safe(ctx.c.name)}</span></div></div><nav class="resident-nav"><a href="#/morador/home">⌂ Início</a><a href="#/morador/announcements">📢 Comunicados</a><a href="#/morador/assemblies" class="active">🏛️ Assembleias</a><a href="#/morador/calls">🎫 Meus chamados</a><a href="#/morador/calendar">📅 Calendário</a><a href="#/morador/documents">📄 Documentos</a><a href="#/morador/notifications">🔔 Notificações</a></nav></aside><main class="resident-main"><header class="resident-top"><div><div class="eyebrow">${safe(ctx.c.name)}</div><h1>Assembleias e votações</h1><p class="muted">Consulte pautas abertas e vote somente quando sua unidade estiver habilitada.</p></div></header>${content}</main></div>`}
  async function residentPage(){
    const ctx=await residentCtx();if(!ctx)return;const [{data:assemblies},{data:items},{data:attendance},{data:results},{data:votes}]=await Promise.all([client.from('assemblies').select('*').eq('condominium_id',ctx.m.condominium_id).in('visibility',['residents','all']).order('scheduled_at',{ascending:false}),client.from('assembly_agenda_items').select('*').eq('condominium_id',ctx.m.condominium_id).neq('status','draft').order('sort_order'),client.from('assembly_attendance').select('*').eq('representative_user_id',ctx.user.id),client.from('assembly_vote_results').select('*').eq('condominium_id',ctx.m.condominium_id),client.from('assembly_votes').select('agenda_item_id,unit_id,choice').eq('voter_user_id',ctx.user.id)]);
    const attMap=new Map((attendance||[]).map(a=>[a.assembly_id,a])),voteMap=new Map((votes||[]).map(v=>[`${v.agenda_item_id}:${v.unit_id}`,v.choice]));const html=(assemblies||[]).map(a=>{const its=(items||[]).filter(i=>i.assembly_id===a.id),att=attMap.get(a.id);return `<article class="panel" style="margin-bottom:14px"><div class="panel-head"><div><div class="eyebrow">${fmt(a.scheduled_at)}</div><h2>${safe(a.title)}</h2><div class="muted small">${safe(a.location||'Local a definir')}</div></div><span class="badge ${a.status==='held'?'good':a.status==='in_progress'?'warn':'attention'}">${safe(statusLabel[a.status]||a.status)}</span></div><div class="panel-body">${att?`<div class="database-explainer"><div class="database-icon">✓</div><div><strong>Sua representação está registrada.</strong><p>Unidade habilitada com peso ${Number(att.vote_weight)}${att.can_vote?' para votar.':' sem direito a voto nesta assembleia.'}</p></div></div>`:'<p class="muted">Sua conta ainda não está registrada como representante de uma unidade nesta assembleia.</p>'}${its.map(i=>{const r=resultFor(i,results||[]),existing=att?voteMap.get(`${i.id}:${att.unit_id}`):null,canVote=att?.can_vote&&i.status==='open'&&['called','in_progress'].includes(a.status);return `<div class="card" style="margin-top:12px"><strong>${safe(i.title)}</strong>${i.description?`<p class="muted" style="margin-top:5px">${safe(i.description)}</p>`:''}${canVote?`<div class="row-actions" style="margin-top:10px"><button class="btn ${existing==='yes'?'btn-primary':''}" onclick="castResidentAssemblyVote('${i.id}','${att.unit_id}','yes')">Sim</button><button class="btn ${existing==='no'?'btn-primary':''}" onclick="castResidentAssemblyVote('${i.id}','${att.unit_id}','no')">Não</button><button class="btn ${existing==='abstain'?'btn-primary':''}" onclick="castResidentAssemblyVote('${i.id}','${att.unit_id}','abstain')">Abstenção</button></div>`:`<div class="muted small" style="margin-top:8px">${safe(agendaStatus[i.status]||i.status)}${existing?` • Seu voto: ${safe(choiceLabel[existing])}`:''}</div>`}${i.result_visibility==='live'||(i.result_visibility==='after_close'&&i.status==='closed')?`<div class="muted small" style="margin-top:8px">Resultado: ${r.yes_votes} Sim • ${r.no_votes} Não • ${r.abstain_votes} abstenção</div>`:''}</div>`}).join('')}</div></article>`}).join('')||'<div class="empty">Nenhuma assembleia disponível.</div>';$('#app').innerHTML=residentShell(ctx,html);
  }
  window.castResidentAssemblyVote=async function(itemId,unitId,choice){const {error}=await client.rpc('cast_assembly_vote',{p_agenda_item_id:itemId,p_unit_id:unitId,p_choice:choice});if(error)return flash(error.message);flash('Voto registrado.');residentPage()};

  window.assemblyVotingPage=listPage;
  window.assemblyVotingWorkspace=workspace;
  window.residentAssembliesPage=residentPage;
})();