const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const KEY='condo_mvp_v2';
const DB_NAME='condo_workspace_files_v1';
const DB_STORE='files';

const iso=d=>{const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),da=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${da}`};
const addDays=n=>{const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+n);return iso(d)};
const br=s=>{if(!s)return'—';const[y,m,d]=s.split('-');return`${d}/${m}/${y}`};
const days=s=>{const a=new Date();a.setHours(0,0,0,0);const b=new Date(s+'T00:00:00');return Math.ceil((b-a)/86400000)};
const uid=p=>`${p}_${Math.random().toString(36).slice(2,10)}`;
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const initials=name=>name.trim().split(/\s+/).slice(0,2).map(x=>x[0]?.toUpperCase()||'').join('')||'S';

function emptyData(){return{
  version:2,
  onboardingComplete:false,
  onboardingStep:1,
  onboardingCondoId:null,
  user:{name:'',initials:'S'},
  condos:[],maintenances:[],calls:[],tasks:[],documents:[],assemblies:[],timeline:[],folders:[],files:[]
}}
function load(){const r=localStorage.getItem(KEY);if(r){try{return JSON.parse(r)}catch(e){}}const d=emptyData();save(d);return d}
function save(d){localStorage.setItem(KEY,JSON.stringify(d))}
let data=load();

const condo=id=>data.condos.find(c=>c.id===id);
const recur=v=>({none:'Única',weekly:'Semanal',monthly:'Mensal',bimonthly:'Bimestral',quarterly:'Trimestral',semiannual:'Semestral',annual:'Anual'})[v]||v;
const statusLabel=s=>({good:'Em dia',warn:'Atenção',bad:'Urgente'})[s]||s;
function urgency(m){if(m.status==='done')return{level:'good',label:'Concluída'};const n=days(m.nextDate);if(n<0)return{level:'bad',label:`Vencida há ${Math.abs(n)} dia${Math.abs(n)===1?'':'s'}`};if(n===0)return{level:'bad',label:'Hoje'};if(n===1)return{level:'bad',label:'Amanhã'};if(n<=2)return{level:'warn',label:`Em ${n} dias`};if(n<=7)return{level:'attention',label:`Em ${n} dias`};return{level:'good',label:`Em ${n} dias`}}
function alerts(cid=null){return data.maintenances.filter(m=>m.status!=='done'&&(!cid||m.condoId===cid)).map(m=>({...m,left:days(m.nextDate)})).filter(m=>m.left<=7).sort((a,b)=>a.left-b.left)}

const RECOMMENDATIONS={
  maintenance:[
    {title:'Inspeção dos elevadores',category:'Elevadores',recurrence:'monthly',after:30,reminders:[7,2]},
    {title:'Inspeção e conferência dos extintores',category:'Extintores',recurrence:'monthly',after:30,reminders:[7,2]},
    {title:"Limpeza da caixa d'água",category:'Hidráulica',recurrence:'semiannual',after:180,reminders:[30,7,2]},
    {title:'Dedetização das áreas comuns',category:'Dedetização',recurrence:'quarterly',after:90,reminders:[30,7,2]},
    {title:'Revisão dos portões e acessos',category:'Portões',recurrence:'monthly',after:30,reminders:[7,2]},
    {title:'Inspeção das bombas hidráulicas',category:'Bombas',recurrence:'monthly',after:30,reminders:[7,2]},
    {title:'Teste da iluminação de emergência',category:'Elétrica',recurrence:'monthly',after:30,reminders:[7,2]}
  ],
  tasks:[
    {title:'Inspeção visual das áreas comuns',recurrence:'weekly',after:7},
    {title:'Conferir inadimplência e pendências financeiras',recurrence:'monthly',after:30},
    {title:'Revisar contratos próximos do vencimento',recurrence:'monthly',after:30},
    {title:'Conferir documentos e licenças obrigatórias',recurrence:'monthly',after:30},
    {title:'Revisar chamados ainda não resolvidos',recurrence:'weekly',after:7}
  ]
};

function openDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(DB_STORE))db.createObjectStore(DB_STORE,{keyPath:'id'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function dbPut(id,blob){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(DB_STORE,'readwrite');tx.objectStore(DB_STORE).put({id,blob});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
async function dbGet(id){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(DB_STORE,'readonly');const req=tx.objectStore(DB_STORE).get(id);req.onsuccess=()=>resolve(req.result?.blob||null);req.onerror=()=>reject(req.error)})}
async function dbDelete(id){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(DB_STORE,'readwrite');tx.objectStore(DB_STORE).delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}

function renderOnboarding(){
  const step=data.onboardingStep||1;
  document.body.classList.add('onboarding-body');
  if(step===1)return onboardingName();
  if(step===2)return onboardingCondo();
  return onboardingRecommendations(data.onboardingCondoId);
}
function onboardingShell(content,step){
  const labels=['Seu perfil','Primeiro condomínio','Rotinas recomendadas'];
  return `<div class="onboarding-page"><div class="onboarding-wrap"><div class="onboarding-brand"><div class="brand-mark">SG</div><div><strong>Gestão Condominial</strong><span>Configuração inicial</span></div></div><div class="onboarding-progress">${labels.map((x,i)=>`<div class="onboarding-step ${step===i+1?'active':step>i+1?'done':''}"><b>${i+1}</b><span>${x}</span></div>`).join('')}</div>${content}</div></div>`
}
function onboardingName(){
  $('#app').innerHTML=onboardingShell(`<section class="onboarding-card"><div class="eyebrow">Bem-vindo</div><h1>Como podemos te chamar?</h1><p class="muted">Esse nome será usado no seu painel e como responsável padrão das tarefas e manutenções.</p><form id="name-form" class="onboarding-form"><div class="field"><label>Seu nome</label><input name="name" required autofocus placeholder="Ex.: Marcos Silva"></div><button class="btn btn-primary btn-lg" type="submit">Continuar →</button></form></section>`,1);
  $('#name-form').onsubmit=e=>{e.preventDefault();const name=new FormData(e.target).get('name').trim();if(!name)return;data.user={name,initials:initials(name)};data.onboardingStep=2;save(data);renderOnboarding()}
}
function onboardingCondo(){
  $('#app').innerHTML=onboardingShell(`<section class="onboarding-card wide"><div class="eyebrow">Condomínio</div><h1>Cadastre um condomínio</h1><p class="muted">Comece com as informações básicas. Depois você poderá editar e complementar tudo pelo Workspace do condomínio.</p><form id="condo-form" class="form-grid onboarding-form"><div class="field full"><label>Nome do condomínio</label><input name="name" required placeholder="Ex.: Residencial Aurora"></div><div class="field full"><label>Endereço</label><input name="address" required placeholder="Rua, número, bairro, cidade"></div><div class="field"><label>CNPJ <span class="muted">(opcional)</span></label><input name="cnpj" placeholder="00.000.000/0000-00"></div><div class="field"><label>Telefone <span class="muted">(opcional)</span></label><input name="phone" placeholder="(51) 99999-9999"></div><div class="field"><label>Quantidade de unidades</label><input name="units" type="number" min="0" value="0"></div><div class="field"><label>Blocos / torres</label><input name="blocks" type="number" min="0" value="1"></div><div class="field"><label>Quantidade aproximada de moradores</label><input name="residents" type="number" min="0" value="0"></div><div class="field"><label>E-mail administrativo</label><input name="email" type="email" placeholder="condominio@email.com"></div><div class="field full"><button class="btn btn-primary btn-lg" type="submit">Salvar e configurar rotinas →</button></div></form></section>`,2);
  $('#condo-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);const id=uid('condo');const c={id,name:f.get('name').trim(),address:f.get('address').trim(),cnpj:f.get('cnpj').trim(),phone:f.get('phone').trim(),units:Number(f.get('units'))||0,blocks:Number(f.get('blocks'))||0,residents:Number(f.get('residents'))||0,email:f.get('email').trim(),status:'good',balance:0};data.condos.push(c);data.folders.push({id:uid('folder'),condoId:id,parentId:null,name:'Documentos Gerais',createdAt:iso(new Date())});data.onboardingCondoId=id;data.onboardingStep=3;save(data);renderOnboarding()}
}
function onboardingRecommendations(cid){
  const c=condo(cid);if(!c){data.onboardingStep=2;save(data);return renderOnboarding()}
  const maint=RECOMMENDATIONS.maintenance.map((r,i)=>`<label class="recommend-card"><input type="checkbox" name="maint" value="${i}" checked><div><strong>${esc(r.title)}</strong><span>${recur(r.recurrence)} • alerta padrão 2 dias antes</span></div><input class="recommend-date" type="date" name="maintDate_${i}" value="${addDays(r.after)}" onclick="event.stopPropagation()"></label>`).join('');
  const tasks=RECOMMENDATIONS.tasks.map((r,i)=>`<label class="recommend-card"><input type="checkbox" name="task" value="${i}" checked><div><strong>${esc(r.title)}</strong><span>${recur(r.recurrence)}</span></div><input class="recommend-date" type="date" name="taskDate_${i}" value="${addDays(r.after)}" onclick="event.stopPropagation()"></label>`).join('');
  $('#app').innerHTML=onboardingShell(`<section class="onboarding-card extra-wide"><div class="eyebrow">Rotinas recomendadas</div><h1>Vamos deixar ${esc(c.name)} preparado?</h1><p class="muted">Selecionamos rotinas comuns para não começar do zero. Você pode desmarcar qualquer item, alterar a primeira data e editar tudo depois.</p><div class="creation-hint"><div>➕</div><div><strong>Você nunca fica preso a estas sugestões.</strong><span>Depois, novas rotinas podem ser criadas em <b>Manutenções → + Nova manutenção</b> e <b>Tarefas → + Nova tarefa</b>, tanto no painel geral quanto dentro do condomínio.</span></div></div><form id="recommend-form"><div class="recommend-columns"><div><div class="section-title"><h2>🔧 Manutenções recorrentes</h2></div><div class="recommend-list">${maint}</div></div><div><div class="section-title"><h2>✓ Tarefas recorrentes</h2></div><div class="recommend-list">${tasks}</div></div></div><div class="onboarding-actions"><button type="button" class="btn" id="skip-recommend">Pular sugestões</button><button class="btn btn-primary btn-lg" type="submit">Adicionar selecionadas</button></div></form></section>`,3);
  const finish=(add)=>{if(add){const form=$('#recommend-form');const fd=new FormData(form);fd.getAll('maint').forEach(v=>{const i=Number(v),r=RECOMMENDATIONS.maintenance[i];data.maintenances.push({id:uid('m'),condoId:cid,title:r.title,category:r.category,supplier:'',responsible:data.user.name,nextDate:fd.get(`maintDate_${i}`)||addDays(r.after),recurrence:r.recurrence,status:'scheduled',reminders:r.reminders,notes:'Rotina sugerida durante a configuração inicial.'})});fd.getAll('task').forEach(v=>{const i=Number(v),r=RECOMMENDATIONS.tasks[i];data.tasks.push({id:uid('t'),condoId:cid,title:r.title,dueDate:fd.get(`taskDate_${i}`)||addDays(r.after),status:'pending',priority:'normal',recurrence:r.recurrence,reminders:[2]})})}data.timeline.unshift({id:uid('tl'),condoId:cid,text:'Configuração inicial do condomínio concluída.',date:iso(new Date())});save(data);showOnboardingFinish(cid)};
  $('#recommend-form').onsubmit=e=>{e.preventDefault();finish(true)};$('#skip-recommend').onclick=()=>finish(false)
}
function showOnboardingFinish(cid){
  const c=condo(cid);$('#app').innerHTML=onboardingShell(`<section class="onboarding-card"><div class="success-mark">✓</div><h1>${esc(c.name)} está pronto!</h1><p class="muted">Você pode adicionar outro condomínio agora ou entrar no painel. Todas as informações continuam editáveis depois.</p><div class="onboarding-actions stacked-mobile"><button class="btn" id="another-condo">+ Adicionar outro condomínio</button><button class="btn btn-primary btn-lg" id="finish-onboarding">Ir para o painel →</button></div></section>`,3);$('#another-condo').onclick=()=>{data.onboardingStep=2;data.onboardingCondoId=null;save(data);renderOnboarding()};$('#finish-onboarding').onclick=()=>{data.onboardingComplete=true;data.onboardingStep=4;save(data);document.body.classList.remove('onboarding-body');location.hash='#/';route()}
}

function shell(content,active='dashboard',cid=null){
  const c=cid?condo(cid):null;
  const main=[['dashboard','⌂','Visão geral','#/'],['condos','▦','Condomínios','#/condominios'],['calendar','◫','Calendário','#/calendario'],['maintenance','⚒','Manutenções','#/manutencoes'],['calls','◉','Chamados','#/chamados'],['tasks','✓','Tarefas','#/tarefas']];
  const sub=c?[['condo-overview','⌂','Resumo',`#/condominio/${cid}`],['condo-calendar','◫','Calendário',`#/condominio/${cid}/calendario`],['condo-maintenance','⚒','Manutenções',`#/condominio/${cid}/manutencoes`],['condo-tasks','✓','Tarefas',`#/condominio/${cid}/tarefas`],['condo-calls','◉','Chamados',`#/condominio/${cid}/chamados`],['condo-docs','▤','Documentos',`#/condominio/${cid}/documentos`],['condo-files','◈','Base de dados',`#/condominio/${cid}/arquivos`],['condo-history','↺','Histórico',`#/condominio/${cid}/historico`]]:[];
  const links=a=>a.map(([id,ic,t,h])=>`<a href="${h}" class="${active===id?'active':''}"><span>${ic}</span>${t}</a>`).join('');
  return`<div class="app-shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">SG</div><div><strong>Gestão Condominial</strong><span>Portal do Síndico</span></div></div><div class="nav-section">Principal</div><nav class="nav">${links(main)}</nav>${c?`<div class="nav-section">Workspace</div><div class="workspace-label">${esc(c.name)}</div><nav class="nav">${links(sub)}</nav>`:''}<div class="sidebar-footer"><small>Sessão atual</small><strong>${esc(data.user.name)}</strong><small>Síndico profissional</small></div></aside><main class="main"><div class="mobile-top"><div class="brand"><div class="brand-mark">SG</div><div><strong>Gestão Condominial</strong><span>Portal do Síndico</span></div></div><button class="icon-btn" onclick="location.hash='#/condominios'">▦</button></div>${content}</main></div>`
}
function topbar(title,sub,eye='Painel do Síndico',actions=''){return`<header class="topbar"><div><div class="eyebrow">${eye}</div><h1>${title}</h1><div class="muted small" style="margin-top:5px">${sub}</div></div><div class="top-actions">${actions}<button class="icon-btn" onclick="location.hash='#/manutencoes'">🔔</button><div class="avatar">${esc(data.user.initials)}</div></div></header>`}
function createHint(type,cid=''){const isM=type==='maintenance';return `<div class="inline-create-hint"><span>${isM?'🔧':'✓'}</span><div><strong>Precisa cadastrar algo novo?</strong><small>Use o botão <b>${isM?'+ Nova manutenção':'+ Nova tarefa'}</b> no topo desta tela. Você pode criar itens a qualquer momento.</small></div></div>`}

function dashboard(){
  const open=data.calls.filter(c=>c.status!=='closed').length,al=alerts(),urg=al.filter(a=>a.left<=2).length,tasks=data.tasks.filter(t=>t.status!=='done').length;
  const cards=data.condos.map(c=>{const cc=data.calls.filter(x=>x.condoId===c.id&&x.status!=='closed').length,mm=data.maintenances.filter(x=>x.condoId===c.id&&x.status!=='done'&&days(x.nextDate)<=7).length,pp=alerts(c.id).filter(x=>x.left<=2).length;return`<a class="condo-card" href="#/condominio/${c.id}"><div class="condo-top"><div class="condo-id"><div class="building">🏢</div><div><strong>${esc(c.name)}</strong><small>${c.units} unidades</small></div></div><span class="badge ${c.status}">${statusLabel(c.status)}</span></div><div class="mini-stats"><div class="mini"><strong>${cc}</strong><span>Chamados</span></div><div class="mini"><strong>${mm}</strong><span>Manutenções</span></div><div class="mini"><strong>${pp}</strong><span>Urgências</span></div></div></a>`}).join('');
  const alertHtml=al.length?al.map(m=>{const u=urgency(m),c=condo(m.condoId),cls=m.left<=1?'critical':m.left<=2?'soon':'watch';return`<div class="alert-card ${cls}"><div class="alert-head"><div><strong>${esc(m.title)}</strong><p>${esc(c.name)} • ${br(m.nextDate)}</p></div><span class="badge ${u.level}">${u.label}</span></div></div>`}).join(''):'<div class="empty">Nenhum alerta nos próximos 7 dias.</div>';
  $('#app').innerHTML=shell(`${topbar(`Buenas, ${esc(data.user.name.split(' ')[0])} 👋`,'Aqui está o resumo consolidado da sua gestão hoje.','Painel do Síndico','<button class="btn btn-primary" onclick="openCondoModal()">+ Novo condomínio</button>')}<section class="metrics"><article class="metric"><div class="metric-top"><div><span>Condomínios ativos</span><strong>${data.condos.length}</strong></div><div class="icon blue">🏢</div></div></article><article class="metric"><div class="metric-top"><div><span>Chamados abertos</span><strong>${open}</strong></div><div class="icon orange">🎫</div></div></article><article class="metric"><div class="metric-top"><div><span>Alertas em até 2 dias</span><strong>${urg}</strong></div><div class="icon red">⚠</div></div></article><article class="metric"><div class="metric-top"><div><span>Tarefas pendentes</span><strong>${tasks}</strong></div><div class="icon green">✓</div></div></article></section><section class="grid-2"><div><article class="panel"><div class="panel-head"><div><h2>Meus condomínios</h2><div class="muted small">Acesse o Workspace de cada operação.</div></div><button class="btn btn-soft" onclick="openCondoModal()">+ Adicionar</button></div><div class="panel-body"><div class="condo-grid">${cards||'<div class="empty">Cadastre seu primeiro condomínio.</div>'}</div></div></article></div><aside><article class="panel"><div class="panel-head"><div><h2>Atenção necessária</h2><div class="muted small">Alertas automáticos dos próximos 7 dias.</div></div></div><div class="panel-body">${alertHtml}</div></article></aside></section>`,'dashboard')
}

function condosPage(){
  const cards=data.condos.map(c=>`<a class="condo-card" href="#/condominio/${c.id}"><div class="condo-top"><div class="condo-id"><div class="building">🏢</div><div><strong>${esc(c.name)}</strong><small>${esc(c.address)}</small></div></div><span class="badge ${c.status}">${statusLabel(c.status)}</span></div><div class="mini-stats"><div class="mini"><strong>${c.units}</strong><span>Unidades</span></div><div class="mini"><strong>${c.residents}</strong><span>Moradores</span></div><div class="mini"><strong>${data.folders.filter(f=>f.condoId===c.id).length}</strong><span>Pastas</span></div></div></a>`).join('');
  $('#app').innerHTML=shell(`${topbar('Condomínios','Todos os condomínios administrados em uma única visão.','Gestão','<button class="btn btn-primary" onclick="openCondoModal()">+ Novo condomínio</button>')}<article class="panel"><div class="panel-head"><h2>Condomínios ativos</h2></div><div class="panel-body"><div class="condo-grid">${cards}</div></div></article>`,'condos')
}

function maintenanceTable(list){if(!list.length)return'<div class="empty">Nenhuma manutenção cadastrada.</div>';return`<div class="table-wrap"><table class="table"><thead><tr><th>Manutenção</th><th>Condomínio</th><th>Próxima data</th><th>Recorrência</th><th>Status</th><th>Ações</th></tr></thead><tbody>${list.map(m=>{const u=urgency(m);return`<tr><td><strong>${esc(m.title)}</strong><div class="list-sub">${esc(m.category)}</div></td><td>${esc(condo(m.condoId)?.name||'—')}</td><td>${br(m.nextDate)}</td><td>${recur(m.recurrence)}</td><td><span class="badge ${u.level}">${u.label}</span></td><td><div class="row-actions"><button class="btn btn-soft" onclick="createMaintenanceRecord('${m.id}')">📁 Registrar</button><button class="btn" onclick="completeMaintenance('${m.id}')">Concluir</button></div></td></tr>`}).join('')}</tbody></table></div>`}
function maintenancesPage(cid=null){const list=data.maintenances.filter(m=>!cid||m.condoId===cid).sort((a,b)=>a.nextDate.localeCompare(b.nextDate));const c=cid?condo(cid):null;$('#app').innerHTML=shell(`${topbar('Manutenções',c?`Rotinas preventivas e corretivas de ${esc(c.name)}.`:'Controle consolidado das manutenções.','Operação',`<button class="btn btn-primary" onclick="openMaintenanceModal('${cid||''}')">+ Nova manutenção</button>`)}${createHint('maintenance',cid)}<article class="panel"><div class="panel-head"><div><h2>Agenda de manutenção</h2><div class="muted small">Alertas automáticos destacam itens quando faltam 7, 2 e 1 dia.</div></div></div><div class="panel-body">${maintenanceTable(list)}</div></article>`,cid?'condo-maintenance':'maintenance',cid)}

function tasksTable(list){if(!list.length)return'<div class="empty">Nenhuma tarefa cadastrada.</div>';return`<div class="table-wrap"><table class="table"><thead><tr><th>Tarefa</th><th>Condomínio</th><th>Prazo</th><th>Recorrência</th><th>Prioridade</th><th>Status</th><th></th></tr></thead><tbody>${list.map(t=>`<tr><td><strong>${esc(t.title)}</strong></td><td>${esc(condo(t.condoId)?.name||'—')}</td><td>${br(t.dueDate)}</td><td>${recur(t.recurrence||'none')}</td><td>${esc(t.priority)}</td><td>${esc(t.status)}</td><td><button class="btn" onclick="completeTask('${t.id}')">Concluir</button></td></tr>`).join('')}</tbody></table></div>`}
function tasksPage(cid=null){const list=data.tasks.filter(t=>!cid||t.condoId===cid).sort((a,b)=>a.dueDate.localeCompare(b.dueDate));const c=cid?condo(cid):null;$('#app').innerHTML=shell(`${topbar('Tarefas',c?`Rotinas e pendências de ${esc(c.name)}.`:'Tarefas operacionais de todos os condomínios.','Operação',`<button class="btn btn-primary" onclick="openTaskModal('${cid||''}')">+ Nova tarefa</button>`)}${createHint('task',cid)}<article class="panel"><div class="panel-head"><h2>Tarefas</h2></div><div class="panel-body">${tasksTable(list)}</div></article>`,cid?'condo-tasks':'tasks',cid)}

function condoOverview(id){const c=condo(id);if(!c)return location.hash='#/';const al=alerts(id),ms=data.maintenances.filter(x=>x.condoId===id&&x.status!=='done'),ts=data.tasks.filter(x=>x.condoId===id&&x.status!=='done'),files=data.files.filter(x=>x.condoId===id),folders=data.folders.filter(x=>x.condoId===id);const alertHtml=al.length?al.map(m=>{const u=urgency(m);return`<div class="alert-card ${m.left<=1?'critical':m.left<=2?'soon':'watch'}"><div class="alert-head"><div><strong>${esc(m.title)}</strong><p>${br(m.nextDate)} • ${esc(m.supplier||'Sem fornecedor')}</p></div><span class="badge ${u.level}">${u.label}</span></div></div>`}).join(''):'<div class="empty">Tudo em dia por aqui.</div>';$('#app').innerHTML=shell(`${topbar(esc(c.name),esc(c.address),'Workspace do condomínio',`<button class="btn btn-primary" onclick="openMaintenanceModal('${id}')">+ Manutenção</button>`)}<div class="workspace-hero"><div><span class="workspace-badge">Workspace</span><h2>Central operacional do condomínio</h2><p>Manutenções, tarefas, calendário, documentos e a base de arquivos ficam reunidos aqui.</p></div><a class="btn btn-dark" href="#/condominio/${id}/arquivos">◈ Abrir base de dados</a></div><div class="kpi-strip" style="margin-bottom:18px"><div class="kpi-pill"><strong>${c.units}</strong><span>Unidades</span></div><div class="kpi-pill"><strong>${al.filter(x=>x.left<=2).length}</strong><span>Alertas urgentes</span></div><div class="kpi-pill"><strong>${ms.length}</strong><span>Manutenções ativas</span></div><div class="kpi-pill"><strong>${ts.length}</strong><span>Tarefas pendentes</span></div><div class="kpi-pill"><strong>${folders.length}</strong><span>Pastas</span></div><div class="kpi-pill"><strong>${files.length}</strong><span>Arquivos</span></div></div><section class="grid-2"><div><article class="panel"><div class="panel-head"><h2>Atenção necessária</h2></div><div class="panel-body">${alertHtml}</div></article><article class="panel"><div class="panel-head"><h2>Próximas manutenções</h2><a class="btn btn-soft" href="#/condominio/${id}/manutencoes">Gerenciar</a></div><div class="panel-body">${maintenanceTable(ms.slice(0,4))}</div></article></div><aside><article class="panel"><div class="panel-head"><div><h2>Base de dados</h2><div class="muted small">Arquivos e registros do condomínio.</div></div></div><div class="panel-body"><div class="database-summary"><div class="database-icon">◈</div><strong>${folders.length} pastas • ${files.length} arquivos</strong><p>Crie pastas por manutenção, obra, ocorrência ou evento e guarde fotos, vídeos, Word, PDF e outros documentos.</p><a class="btn btn-primary" href="#/condominio/${id}/arquivos">Abrir arquivos</a></div></div></article></aside></section>`,'condo-overview',id)}

let calendarCursor=new Date();
function calendarEvents(cid=null){const e=[];data.maintenances.filter(x=>!cid||x.condoId===cid).forEach(x=>e.push({date:x.nextDate,title:x.title,type:'maintenance'}));data.tasks.filter(x=>!cid||x.condoId===cid).forEach(x=>e.push({date:x.dueDate,title:x.title,type:'task'}));data.assemblies.filter(x=>!cid||x.condoId===cid).forEach(x=>e.push({date:x.date,title:x.title,type:'assembly'}));return e}
function calendarPage(cid=null){const c=cid?condo(cid):null,y=calendarCursor.getFullYear(),m=calendarCursor.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),start=new Date(y,m,1-first.getDay()),end=new Date(y,m,last.getDate()+(6-last.getDay())),ev=calendarEvents(cid),cells=[];for(let d=new Date(start);d<=end;d.setDate(d.getDate()+1)){const key=iso(d),inMonth=d.getMonth()===m,here=ev.filter(x=>x.date===key);cells.push(`<div class="cal-day ${inMonth?'':'out'}"><div class="cal-date">${d.getDate()}</div>${here.map(x=>`<div class="event ${x.type}">${esc(x.title)}</div>`).join('')}</div>`)}const month=new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(new Date(y,m,1));$('#app').innerHTML=shell(`${topbar('Calendário',c?`Agenda de ${esc(c.name)}.`:'Agenda consolidada de todos os condomínios.','Agenda')}<article class="calendar-card" style="padding:18px"><div class="calendar-toolbar"><div><h2 style="text-transform:capitalize">${month}</h2><div class="muted small">Manutenções, tarefas e assembleias.</div></div><div class="calendar-nav"><button class="icon-btn" onclick="moveCalendar(-1,'${cid||''}')">‹</button><button class="btn" onclick="calendarToday('${cid||''}')">Hoje</button><button class="icon-btn" onclick="moveCalendar(1,'${cid||''}')">›</button></div></div><div class="calendar">${['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'].map(x=>`<div class="cal-head">${x}</div>`).join('')}${cells.join('')}</div></article>`,cid?'condo-calendar':'calendar',cid)}
window.moveCalendar=(n,cid)=>{calendarCursor.setMonth(calendarCursor.getMonth()+n);calendarPage(cid||null)};window.calendarToday=cid=>{calendarCursor=new Date();calendarPage(cid||null)};

function callsPage(cid=null){const arr=data.calls.filter(x=>!cid||x.condoId===cid),c=cid?condo(cid):null;$('#app').innerHTML=shell(`${topbar('Chamados',c?`Solicitações de ${esc(c.name)}.`:'Solicitações de todos os condomínios.','Operação')}<article class="panel"><div class="panel-body" style="padding-top:18px">${arr.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Chamado</th><th>Condomínio</th><th>Unidade</th><th>Prioridade</th><th>Status</th></tr></thead><tbody>${arr.map(x=>`<tr><td><strong>${esc(x.title)}</strong></td><td>${esc(condo(x.condoId)?.name||'—')}</td><td>${esc(x.unit||'—')}</td><td>${esc(x.priority)}</td><td>${esc(x.status)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Nenhum chamado cadastrado.</div>'}</div></article>`,cid?'condo-calls':'calls',cid)}
function docsPage(cid){const c=condo(cid),arr=data.documents.filter(x=>x.condoId===cid);$('#app').innerHTML=shell(`${topbar('Documentos',`${esc(c.name)} • documentos com controle de vencimento.`,'Workspace')}<article class="panel"><div class="panel-head"><h2>Documentos controlados</h2></div><div class="panel-body">${arr.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Documento</th><th>Categoria</th><th>Vencimento</th></tr></thead><tbody>${arr.map(x=>`<tr><td><strong>${esc(x.title)}</strong></td><td>${esc(x.category)}</td><td>${br(x.expiry)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Nenhum documento com vencimento cadastrado. Para arquivos gerais, utilize a Base de Dados.</div>'}</div></article>`,'condo-docs',cid)}
function historyPage(cid){const c=condo(cid),arr=data.timeline.filter(x=>x.condoId===cid);$('#app').innerHTML=shell(`${topbar('Histórico',`Linha do tempo da gestão de ${esc(c.name)}.`,'Workspace')}<article class="panel"><div class="panel-body" style="padding-top:20px"><div class="timeline">${arr.length?arr.map(x=>`<div class="timeline-item"><strong>${esc(x.text)}</strong><p>${br(x.date)}</p></div>`).join(''):'<div class="empty">Nenhuma atividade registrada.</div>'}</div></div></article>`,'condo-history',cid)}

function folderPath(cid,folderId){const out=[];let cur=folderId?data.folders.find(f=>f.id===folderId):null;while(cur){out.unshift(cur);cur=cur.parentId?data.folders.find(f=>f.id===cur.parentId):null}return out}
function fileKind(file){const t=file.type||'';if(t.startsWith('image/'))return{icon:'🖼️',label:'Imagem'};if(t.startsWith('video/'))return{icon:'🎬',label:'Vídeo'};if(t.includes('pdf'))return{icon:'📕',label:'PDF'};if(t.includes('word')||/\.docx?$/i.test(file.name))return{icon:'📘',label:'Word'};if(t.includes('sheet')||/\.xlsx?$/i.test(file.name))return{icon:'📗',label:'Planilha'};return{icon:'📄',label:'Arquivo'}}
function fmtSize(n){if(n<1024)return`${n} B`;if(n<1048576)return`${(n/1024).toFixed(1)} KB`;return`${(n/1048576).toFixed(1)} MB`}
function filesPage(cid,folderId=null){const c=condo(cid);if(!c)return;const folders=data.folders.filter(f=>f.condoId===cid&&(f.parentId||null)===(folderId||null));const files=data.files.filter(f=>f.condoId===cid&&(f.folderId||null)===(folderId||null));const crumbs=folderPath(cid,folderId);const folderCards=folders.map(f=>`<button class="file-card folder-card" onclick="openFolder('${cid}','${f.id}')"><div class="file-icon">📁</div><div><strong>${esc(f.name)}</strong><span>${data.files.filter(x=>x.folderId===f.id).length} arquivo(s)</span></div></button>`).join('');const fileCards=files.map(f=>{const k=fileKind(f);return`<div class="file-card"><div class="file-icon">${k.icon}</div><div class="file-info"><strong title="${esc(f.name)}">${esc(f.name)}</strong><span>${k.label} • ${fmtSize(f.size||0)}</span></div><div class="file-actions"><button class="icon-btn small-icon" onclick="previewFile('${f.id}')" title="Abrir">↗</button><button class="icon-btn small-icon danger-icon" onclick="deleteFile('${f.id}')" title="Excluir">×</button></div></div>`}).join('');$('#app').innerHTML=shell(`${topbar('Base de Dados',`Arquivos e registros de ${esc(c.name)}.`,'Workspace',`<button class="btn" onclick="openFolderModal('${cid}','${folderId||''}')">+ Nova pasta</button><button class="btn btn-primary" onclick="triggerUpload('${cid}','${folderId||''}')">↑ Enviar arquivos</button>`)}<div class="database-explainer"><div class="database-icon">◈</div><div><strong>Organize como uma base de conhecimento do condomínio.</strong><p>Exemplo: crie <b>Manutenção 20/05/2026</b> e dentro dela pastas como <b>Documentos</b>, <b>Fotos</b> e <b>Vídeos</b>. Os registros ficam ligados ao condomínio e podem ser abertos a qualquer momento.</p></div></div><div class="breadcrumbs"><button onclick="openFolder('${cid}','')">Base</button>${crumbs.map(f=>`<span>›</span><button onclick="openFolder('${cid}','${f.id}')">${esc(f.name)}</button>`).join('')}</div><article class="panel"><div class="panel-head"><div><h2>${folderId?esc(data.folders.find(f=>f.id===folderId)?.name||'Pasta'):'Arquivos do condomínio'}</h2><div class="muted small">${folders.length} pasta(s) • ${files.length} arquivo(s)</div></div></div><div class="panel-body"><div class="file-grid">${folderCards}${fileCards}${!folderCards&&!fileCards?'<div class="empty file-empty"><div>📂</div><strong>Esta pasta está vazia</strong><span>Crie uma pasta ou envie fotos, vídeos e documentos.</span></div>':''}</div></div></article><input id="file-upload" type="file" multiple hidden>`,'condo-files',cid);const input=$('#file-upload');input.onchange=async e=>{await uploadFiles(cid,folderId,[...e.target.files]);input.value=''}}
window.openFolder=(cid,fid)=>{location.hash=`#/condominio/${cid}/arquivos${fid?'/'+fid:''}`};
window.triggerUpload=(cid,fid)=>$('#file-upload')?.click();
async function uploadFiles(cid,folderId,fileList){if(!fileList.length)return;flash(`Enviando ${fileList.length} arquivo(s)...`);for(const file of fileList){const id=uid('file');try{await dbPut(id,file);data.files.push({id,condoId:cid,folderId:folderId||null,name:file.name,type:file.type,size:file.size,uploadedAt:iso(new Date())})}catch(e){console.error(e);flash('Não foi possível salvar um dos arquivos.')}}data.timeline.unshift({id:uid('tl'),condoId:cid,text:`${fileList.length} arquivo(s) adicionado(s) à Base de Dados.`,date:iso(new Date())});save(data);filesPage(cid,folderId||null)}
window.previewFile=async id=>{const meta=data.files.find(f=>f.id===id);if(!meta)return;const blob=await dbGet(id);if(!blob)return flash('Arquivo não encontrado neste navegador.');const url=URL.createObjectURL(blob);window.open(url,'_blank');setTimeout(()=>URL.revokeObjectURL(url),60000)};
window.deleteFile=async id=>{if(!confirm('Excluir este arquivo?'))return;const meta=data.files.find(f=>f.id===id);await dbDelete(id);data.files=data.files.filter(f=>f.id!==id);save(data);if(meta)filesPage(meta.condoId,meta.folderId||null)};

window.createMaintenanceRecord=function(mid){const m=data.maintenances.find(x=>x.id===mid);if(!m)return;const rootName=`${m.title} - ${br(m.nextDate)}`;let root=data.folders.find(f=>f.condoId===m.condoId&&f.parentId===null&&f.name===rootName);if(!root){root={id:uid('folder'),condoId:m.condoId,parentId:null,name:rootName,createdAt:iso(new Date())};data.folders.push(root);['Documentos','Fotos','Vídeos'].forEach(name=>data.folders.push({id:uid('folder'),condoId:m.condoId,parentId:root.id,name,createdAt:iso(new Date())}));data.timeline.unshift({id:uid('tl'),condoId:m.condoId,text:`Pasta de registro criada para: ${m.title}.`,date:iso(new Date())});save(data)}location.hash=`#/condominio/${m.condoId}/arquivos/${root.id}`};

function modal(content){$('#modal-content').innerHTML=content;$('#modal').classList.remove('hidden');$('#modal').setAttribute('aria-hidden','false')}
function closeModal(){$('#modal').classList.add('hidden');$('#modal').setAttribute('aria-hidden','true')}
document.addEventListener('click',e=>{if(e.target.matches('[data-close-modal]'))closeModal()});
function flash(msg){const el=document.createElement('div');el.className='flash';el.textContent=msg;document.body.appendChild(el);setTimeout(()=>el.remove(),2300)}

window.openCondoModal=function(){modal(`<div class="eyebrow">Novo condomínio</div><h2 style="margin-bottom:16px">Adicionar condomínio</h2><form id="modal-condo" class="form-grid"><div class="field full"><label>Nome</label><input name="name" required></div><div class="field full"><label>Endereço</label><input name="address" required></div><div class="field"><label>Unidades</label><input name="units" type="number" min="0" value="0"></div><div class="field"><label>Moradores</label><input name="residents" type="number" min="0" value="0"></div><div class="field full"><button class="btn btn-primary" type="submit">Criar condomínio</button></div></form>`);$('#modal-condo').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),id=uid('condo');data.condos.push({id,name:f.get('name').trim(),address:f.get('address').trim(),units:Number(f.get('units'))||0,residents:Number(f.get('residents'))||0,status:'good',balance:0});data.folders.push({id:uid('folder'),condoId:id,parentId:null,name:'Documentos Gerais',createdAt:iso(new Date())});save(data);closeModal();openRecommendationModal(id)}};

window.openRecommendationModal=function(cid){
  const c=condo(cid);if(!c)return;
  const maint=RECOMMENDATIONS.maintenance.map((r,i)=>`<label class="recommend-card"><input type="checkbox" name="maint" value="${i}" checked><div><strong>${esc(r.title)}</strong><span>${recur(r.recurrence)} • alerta em 2 dias</span></div><input class="recommend-date" type="date" name="maintDate_${i}" value="${addDays(r.after)}"></label>`).join('');
  const tasks=RECOMMENDATIONS.tasks.map((r,i)=>`<label class="recommend-card"><input type="checkbox" name="task" value="${i}" checked><div><strong>${esc(r.title)}</strong><span>${recur(r.recurrence)}</span></div><input class="recommend-date" type="date" name="taskDate_${i}" value="${addDays(r.after)}"></label>`).join('');
  modal(`<div class="eyebrow">Configuração sugerida</div><h2>Rotinas para ${esc(c.name)}</h2><p class="muted small">Escolha o que faz sentido. Depois você também pode criar manualmente em <b>Manutenções → + Nova manutenção</b> e <b>Tarefas → + Nova tarefa</b>.</p><form id="post-recommend-form"><div class="recommend-columns modal-recommend"><div><h3 style="font-size:13px;margin:16px 0 10px">🔧 Manutenções</h3><div class="recommend-list">${maint}</div></div><div><h3 style="font-size:13px;margin:16px 0 10px">✓ Tarefas</h3><div class="recommend-list">${tasks}</div></div></div><div class="onboarding-actions"><button type="button" class="btn" id="skip-post-recommend">Pular</button><button class="btn btn-primary" type="submit">Adicionar selecionadas</button></div></form>`);
  const finish=add=>{if(add){const fd=new FormData($('#post-recommend-form'));fd.getAll('maint').forEach(v=>{const i=Number(v),r=RECOMMENDATIONS.maintenance[i];data.maintenances.push({id:uid('m'),condoId:cid,title:r.title,category:r.category,supplier:'',responsible:data.user.name,nextDate:fd.get(`maintDate_${i}`)||addDays(r.after),recurrence:r.recurrence,status:'scheduled',reminders:r.reminders,notes:'Rotina sugerida durante o cadastro do condomínio.'})});fd.getAll('task').forEach(v=>{const i=Number(v),r=RECOMMENDATIONS.tasks[i];data.tasks.push({id:uid('t'),condoId:cid,title:r.title,dueDate:fd.get(`taskDate_${i}`)||addDays(r.after),status:'pending',priority:'normal',recurrence:r.recurrence,reminders:[2]})})}data.timeline.unshift({id:uid('tl'),condoId:cid,text:'Condomínio cadastrado e configuração inicial concluída.',date:iso(new Date())});save(data);closeModal();flash('Condomínio pronto.');location.hash=`#/condominio/${cid}`};
  $('#post-recommend-form').onsubmit=e=>{e.preventDefault();finish(true)};$('#skip-post-recommend').onclick=()=>finish(false)
};

window.openMaintenanceModal=function(cid=''){modal(`<div class="eyebrow">Nova manutenção</div><h2 style="margin-bottom:16px">Cadastrar manutenção</h2><form id="maintenance-form" class="form-grid"><div class="field full"><label>Condomínio</label><select name="condoId">${data.condos.map(c=>`<option value="${c.id}" ${c.id===cid?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div><div class="field full"><label>Serviço</label><input name="title" required placeholder="Ex.: Inspeção dos elevadores"></div><div class="field"><label>Categoria</label><select name="category"><option>Elevadores</option><option>Extintores</option><option>Hidráulica</option><option>Dedetização</option><option>Portões</option><option>Bombas</option><option>Elétrica</option><option>Outros</option></select></div><div class="field"><label>Fornecedor</label><input name="supplier"></div><div class="field"><label>Próxima data</label><input name="nextDate" type="date" required value="${addDays(7)}"></div><div class="field"><label>Recorrência</label><select name="recurrence"><option value="none">Única</option><option value="weekly">Semanal</option><option value="monthly" selected>Mensal</option><option value="bimonthly">Bimestral</option><option value="quarterly">Trimestral</option><option value="semiannual">Semestral</option><option value="annual">Anual</option></select></div><div class="field"><label>Responsável</label><input name="responsible" value="${esc(data.user.name)}"></div><div class="field"><label>Lembretes em dias</label><input name="reminders" value="7,2" placeholder="30,7,2"></div><div class="field full"><label>Observações</label><textarea name="notes"></textarea></div><div class="field full"><button class="btn btn-primary" type="submit">Salvar manutenção</button></div></form>`);$('#maintenance-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);data.maintenances.push({id:uid('m'),condoId:f.get('condoId'),title:f.get('title').trim(),category:f.get('category'),supplier:f.get('supplier').trim(),responsible:f.get('responsible').trim(),nextDate:f.get('nextDate'),recurrence:f.get('recurrence'),status:'scheduled',reminders:String(f.get('reminders')).split(',').map(x=>Number(x.trim())).filter(Number.isFinite),notes:f.get('notes').trim()});save(data);closeModal();flash('Manutenção cadastrada.');route()}};
window.openTaskModal=function(cid=''){modal(`<div class="eyebrow">Nova tarefa</div><h2 style="margin-bottom:16px">Cadastrar tarefa</h2><form id="task-form" class="form-grid"><div class="field full"><label>Condomínio</label><select name="condoId">${data.condos.map(c=>`<option value="${c.id}" ${c.id===cid?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div><div class="field full"><label>Tarefa</label><input name="title" required></div><div class="field"><label>Prazo</label><input name="dueDate" type="date" required value="${addDays(7)}"></div><div class="field"><label>Recorrência</label><select name="recurrence"><option value="none">Única</option><option value="weekly">Semanal</option><option value="monthly">Mensal</option><option value="quarterly">Trimestral</option><option value="annual">Anual</option></select></div><div class="field"><label>Prioridade</label><select name="priority"><option value="normal">Normal</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></div><div class="field full"><button class="btn btn-primary" type="submit">Salvar tarefa</button></div></form>`);$('#task-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);data.tasks.push({id:uid('t'),condoId:f.get('condoId'),title:f.get('title').trim(),dueDate:f.get('dueDate'),recurrence:f.get('recurrence'),priority:f.get('priority'),status:'pending',reminders:[2]});save(data);closeModal();flash('Tarefa cadastrada.');route()}};
window.openFolderModal=function(cid,parentId=''){modal(`<div class="eyebrow">Base de dados</div><h2 style="margin-bottom:16px">Criar pasta</h2><form id="folder-form"><div class="field"><label>Nome da pasta</label><input name="name" required autofocus placeholder="Ex.: Manutenção 20/05/2026"></div><div style="margin-top:14px"><button class="btn btn-primary" type="submit">Criar pasta</button></div></form>`);$('#folder-form').onsubmit=e=>{e.preventDefault();const name=new FormData(e.target).get('name').trim();data.folders.push({id:uid('folder'),condoId:cid,parentId:parentId||null,name,createdAt:iso(new Date())});save(data);closeModal();flash('Pasta criada.');filesPage(cid,parentId||null)}};

function nextDate(date,rec){const d=new Date(date+'T12:00:00');if(rec==='weekly')d.setDate(d.getDate()+7);if(rec==='monthly')d.setMonth(d.getMonth()+1);if(rec==='bimonthly')d.setMonth(d.getMonth()+2);if(rec==='quarterly')d.setMonth(d.getMonth()+3);if(rec==='semiannual')d.setMonth(d.getMonth()+6);if(rec==='annual')d.setFullYear(d.getFullYear()+1);return iso(d)}
window.completeMaintenance=id=>{const m=data.maintenances.find(x=>x.id===id);if(!m)return;if(m.recurrence&&m.recurrence!=='none'){m.nextDate=nextDate(m.nextDate,m.recurrence);data.timeline.unshift({id:uid('tl'),condoId:m.condoId,text:`Manutenção concluída: ${m.title}. Próxima ocorrência: ${br(m.nextDate)}.`,date:iso(new Date())})}else{m.status='done';data.timeline.unshift({id:uid('tl'),condoId:m.condoId,text:`Manutenção concluída: ${m.title}.`,date:iso(new Date())})}save(data);flash('Manutenção concluída.');route()};
window.completeTask=id=>{const t=data.tasks.find(x=>x.id===id);if(!t)return;if(t.recurrence&&t.recurrence!=='none'){t.dueDate=nextDate(t.dueDate,t.recurrence)}else t.status='done';save(data);flash('Tarefa concluída.');route()};

function route(){data=load();if(!data.onboardingComplete)return renderOnboarding();document.body.classList.remove('onboarding-body');const p=(location.hash||'#/').replace(/^#\//,'').split('/').filter(Boolean);if(!p.length)return dashboard();if(p[0]==='condominios')return condosPage();if(p[0]==='calendario')return calendarPage();if(p[0]==='manutencoes')return maintenancesPage();if(p[0]==='tarefas')return tasksPage();if(p[0]==='chamados')return callsPage();if(p[0]==='condominio'){const id=p[1],sub=p[2];if(!sub)return condoOverview(id);if(sub==='calendario')return calendarPage(id);if(sub==='manutencoes')return maintenancesPage(id);if(sub==='tarefas')return tasksPage(id);if(sub==='chamados')return callsPage(id);if(sub==='documentos')return docsPage(id);if(sub==='historico')return historyPage(id);if(sub==='arquivos')return filesPage(id,p[3]||null)}dashboard()}
window.addEventListener('hashchange',route);
route();
